### ISSUE TITLE
Enable parallel tests

### ISSUE THREAD

**Issue by NucciTheBoss** [NucciTheBoss/cleantest#3]
Another important feature to add is the support for parallel tests. Running tests sequentially using LXD will take forever as the amount of testlets for each project grows.

This should be easily accomplished using the `multiprocessing` module but extra care will need to be taken to ensure that there is no data racing in the tests. Also, the amount of threads should be controllable via an environment variable and or with the test provider decorators.

**Comment by NucciTheBoss** [comment]
Removed from 0.2.0 milestone due to time constraints and presentations

**Comment by NucciTheBoss** [comment]
Word to the wise. You cannot pickle `Client` objects produced by pylxd since `_APINode` is not callable. The Client object sent in by the `lxd` class will need to be unloaded, or the `LXDHandler` class will need to take care of loading the relevant information for the LXD test environment provider and `lxd` just serves to pass in the information.

Here is a copy of the traceback that I ran into while working with `ProcessPoolExecutor`:

```python
Traceback (most recent call last):
  File "/mnt/d/projects/work/cleantest/tests/lxd/parallel/test_lxd_parallel.py", line 39, in test_parallel_lxd
    results = install_tabulate()
  File "/mnt/d/projects/work/cleantest/src/cleantest/provider/lxd.py", line 89, in wrapper
    return handler.run()
  File "/mnt/d/projects/work/cleantest/src/cleantest/provider/_handler/lxd_handler.py", line 131, in run
    pickle.dumps(self)
TypeError: '_APINode' object is not callable
```

**Comment by NucciTheBoss** [comment]
Parallel tests are working, but now there is a problem with Python being too old on both Focal and Bionic. The easiest way to fix this (I see) is to find a way to package Python as a snap. Not optimal but at least it ensures a consistent experience across distributions.
